export const GET_AUDITORS_REQUEST = 'GET_AUDITORS_REQUEST'
export const GET_AUDITORS_SUCCESS = 'GET_AUDITORS_SUCCESS'
export const GET_AUDITORS_FAILED = 'GET_AUDITORS_FAILED'

export const UPDATE_AUDITOR_REQUEST = 'UPDATE_AUDITOR_REQUEST'
export const UPDATE_AUDITOR_SUCCESS = 'UPDATE_AUDITOR_SUCCESS'
export const UPDATE_AUDITOR_FAILED = 'UPDATE_AUDITOR_FAILED'

export const DELETE_AUDITOR_REQUEST = 'DELETE_AUDITOR_REQUEST'
export const DELETE_AUDITOR_SUCCESS = 'DELETE_AUDITOR_SUCCESS'
export const DELETE_AUDITOR_FAILED = 'DELETE_AUDITOR_FAILED'

export const GET_CALENDAR_DATA_REQUEST = 'GET_CALENDAR_DATA_REQUEST'
export const GET_CALENDAR_DATA_SUCCESS = 'GET_CALENDAR_DATA_SUCCESS'
export const GET_CALENDAR_DATA_FAILED = 'GET_CALENDAR_DATA_FAILED'

export const SAVE_CALENDAR_DATA_REQUEST = 'SAVE_CALENDAR_DATA_REQUEST'
export const SAVE_CALENDAR_DATA_SUCCESS = 'SAVE_CALENDAR_DATA_SUCCESS'
export const SAVE_CALENDAR_DATA_FAILED = 'SAVE_CALENDAR_DATA_FAILED'

export const GET_AUDITOR_SETTINGS_REQUEST = 'GET_AUDITOR_SETTINGS_REQUEST'
export const GET_AUDITOR_SETTINGS_SUCCESS = 'GET_AUDITOR_SETTINGS_SUCCESS'
export const GET_AUDITOR_SETTINGS_FAILED = 'GET_AUDITOR_SETTINGS_FAILED'

export const SAVE_AUDITOR_SETTINGS_REQUEST = 'SAVE_AUDITOR_SETTINGS_REQUEST'
export const SAVE_AUDITOR_SETTINGS_SUCCESS = 'SAVE_AUDITOR_SETTINGS_SUCCESS'
export const SAVE_AUDITOR_SETTINGS_FAILED = 'SAVE_AUDITOR_SETTINGS_FAILED'