export const GET_ALL_DICTIONARY_REQUEST = 'GET_ALL_DICTIONARY_REQUEST'
export const GET_ALL_DICTIONARY_SUCCESS = 'GET_ALL_DICTIONARY_SUCCESS'
export const GET_ALL_DICTIONARY_FAILED = 'GET_ALL_DICTIONARY_FAILED'