export const GET_ALL_PERMISSIONS_REQUEST = 'GET_ALL_PERMISSIONS_REQUEST'
export const GET_ALL_PERMISSIONS_SUCCESS = 'GET_ALL_PERMISSIONS_SUCCESS'
export const GET_ALL_PERMISSIONS_FAILED = 'GET_ALL_PERMISSIONS_FAILED'