export const SEARCH_BUYERS_REQUEST = 'SEARCH_BUYERS_REQUEST'
export const SEARCH_BUYERS_SUCCESS = 'SEARCH_BUYERS_SUCCESS'
export const SEARCH_BUYERS_FAILED = 'SEARCH_BUYERS_FAILED'

export const UPDATE_BUYERS_REQUEST = 'UPDATE_BUYERS_REQUEST'
export const UPDATE_BUYERS_SUCCESS = 'UPDATE_BUYERS_SUCCESS'
export const UPDATE_BUYERS_FAILED = 'UPDATE_BUYERS_FAILED'