export const TENDER_CPV_SEARCH_REQUEST = 'TENDER_CPV_SEARCH_REQUEST'
export const TENDER_CPV_SEARCH_SUCCESS = 'TENDER_CPV_SEARCH_SUCCESS'
export const TENDER_CPV_SEARCH_FAILED = 'TENDER_CPV_SEARCH_FAILED'

export const TENDER_CPV_SEARCH_CLEAR = 'TENDER_CPV_SEARCH_CLEAR'