export const EXPORT_FILE_REQUEST = 'EXPORT_FILE_REQUEST'
export const EXPORT_FILE_SUCCESS = 'EXPORT_FILE_SUCCESS'
export const EXPORT_FILE_FAILED = 'EXPORT_FILE_FAILED'
export const EXPORT_FILE_CLEAR = 'EXPORT_FILE_CLEAR'