
export const OFFICES_REQUEST = 'OFFICES_REQUEST'
export const OFFICES_SUCCESS = 'OFFICES_SUCCESS'
export const OFFICES_FAILED = 'OFFICES_FAILED'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_CLEAR = 'LOGIN_CLEAR'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const LOGOUT_USER = 'LOGOUT_USER'

export const RESET_SEND_EMAIL_REQUEST = 'RESET_SEND_EMAIL_REQUEST'
export const RESET_SEND_EMAIL_SUCCESS = 'RESET_SEND_EMAIL_SUCCESS'
export const RESET_SEND_EMAIL_FAILED = 'RESET_SEND_EMAIL_FAILED'
export const RESET_SEND_EMAIL_CLEAR = 'RESET_SEND_EMAIL_CLEAR'

export const RESET_CHECK_TOKEN_REQUEST = 'RESET_CHECK_TOKEN_REQUEST'
export const RESET_CHECK_TOKEN_SUCCESS = 'RESET_CHECK_TOKEN_SUCCESS'
export const RESET_CHECK_TOKEN_FAILED = 'RESET_CHECK_TOKEN_FAILED'
export const RESET_CHECK_TOKEN_CLEAR = 'RESET_CHECK_TOKEN_CLEAR'

export const RESET_SAVE_NEW_PASSWORD_REQUEST = 'RESET_SAVE_NEW_PASSWORD_REQUEST'
export const RESET_SAVE_NEW_PASSWORD_SUCCESS = 'RESET_SAVE_NEW_PASSWORD_SUCCESS'
export const RESET_SAVE_NEW_PASSWORD_FAILED = 'RESET_SAVE_NEW_PASSWORD_FAILED'
export const RESET_SAVE_NEW_PASSWORD_CLEAR = 'RESET_SAVE_NEW_PASSWORD_CLEAR'

export const AUDITOR_UPDATE_PASSWORD_REQUEST = 'AUDITOR_UPDATE_PASSWORD_REQUEST'
export const AUDITOR_UPDATE_PASSWORD_SUCCESS = 'AUDITOR_UPDATE_PASSWORD_SUCCESS'
export const AUDITOR_UPDATE_PASSWORD_FAILED = 'AUDITOR_UPDATE_PASSWORD_FAILED'
export const AUDITOR_UPDATE_PASSWORD_CLEAR = 'AUDITOR_UPDATE_PASSWORD_CLEAR'
