export const GET_BUYERS_BY_SEARCH_REQUEST = 'GET_BUYERS_BY_SEARCH_REQUEST'
export const GET_BUYERS_BY_SEARCH_SUCCESS = 'GET_BUYERS_BY_SEARCH_SUCCESS'
export const GET_BUYERS_BY_SEARCH_FAILED = 'GET_BUYERS_BY_SEARCH_FAILED'

export const BUYERS_BY_SEARCH_CLEAR = 'BUYERS_BY_SEARCH_CLEAR'