// -------------- Current date

export const SET_CURRENT_DATE = 'SET_CURRENT_DATE'

// -------------- Main page

export const GET_DATA_FOR_MAIN_PAGE_REQUEST = 'GET_DATA_FOR_MAIN_PAGE_REQUEST'
export const GET_DATA_FOR_MAIN_PAGE_ERROR = 'GET_DATA_FOR_MAIN_PAGE_ERROR'
export const GET_DATA_FOR_MAIN_PAGE_SUCCESS = 'GET_DATA_FOR_MAIN_PAGE_SUCCESS'

export const SEND_FEEDBACK_QUESTION_REQUEST = 'SEND_FEEDBACK_QUESTION_REQUEST'
export const SEND_FEEDBACK_QUESTION_ERROR = 'SEND_FEEDBACK_QUESTION_ERROR'
export const SEND_FEEDBACK_QUESTION_SUCCESS = 'SEND_FEEDBACK_QUESTION_SUCCESS'

// -------------- Resources page

export const GET_DATA_FOR_RESOURCES_PAGE_REQUEST = 'GET_DATA_FOR_RESOURCES_PAGE_REQUEST'
export const GET_DATA_FOR_RESOURCES_PAGE_ERROR = 'GET_DATA_FOR_RESOURCES_PAGE_ERROR'
export const GET_DATA_FOR_RESOURCES_PAGE_SUCCESS = 'GET_DATA_FOR_RESOURCES_PAGE_SUCCESS'

// -------------- Comparative dynamics page

export const GET_DATA_FOR_COMPARATIVE_DYNAMICS_PAGE_REQUEST = 'GET_DATA_FOR_COMPARATIVE_DYNAMICS_PAGE_REQUEST'
export const GET_DATA_FOR_COMPARATIVE_DYNAMICS_PAGE_ERROR = 'GET_DATA_FOR_COMPARATIVE_DYNAMICS_PAGE_ERROR'
export const GET_DATA_FOR_COMPARATIVE_DYNAMICS_PAGE__SUCCESS = 'GET_DATA_FOR_COMPARATIVE_DYNAMICS_PAGE__SUCCESS'

export const GET_REGIONS_DATA_COMPARATIVE_DYNAMICS_PAGE_REQUEST = 'GET_REGIONS_DATA_COMPARATIVE_DYNAMICS_PAGE_REQUEST'
export const GET_REGIONS_DATA_COMPARATIVE_DYNAMICS_PAGE_ERROR = 'GET_REGIONS_DATA_COMPARATIVE_DYNAMICS_PAGE_ERROR'
export const GET_REGIONS_DATA_COMPARATIVE_DYNAMICS_PAGE_SUCCESS = 'GET_REGIONS_DATA_COMPARATIVE_DYNAMICS_PAGE_SUCCESS'

// -------------- Monitoring market page

export const GET_DATA_FOR_MONITORING_MARKET_PAGE_REQUEST = 'GET_DATA_FOR_MONITORING_MARKET_PAGE_REQUEST'
export const GET_DATA_FOR_MONITORING_MARKET_PAGE_ERROR = 'GET_DATA_FOR_MONITORING_MARKET_PAGE__ERROR'
export const GET_DATA_FOR_MONITORING_MARKET_PAGE_SUCCESS = 'GET_DATA_FOR_MONITORING_MARKET_PAGE__SUCCESS'

export const GET_REGIONS_DATA_FOR_MONITORING_MARKET_PAGE_REQUEST = 'GET_REGIONS_DATA_FOR_MONITORING_MARKET_PAGE_REQUEST'
export const GET_REGIONS_DATA_FOR_MONITORING_MARKET_PAGE_ERROR = 'GET_REGIONS_DATA_FOR_MONITORING_MARKET_PAGE__ERROR'
export const GET_REGIONS_DATA_FOR_MONITORING_MARKET_PAGE_SUCCESS = 'GET_REGIONS_DATA_FOR_MONITORING_MARKET_PAGE__SUCCESS'

export const GET_PROCEDURE_DRILL_DATA_REQUEST = 'GET_PROCEDURE_DRILL_DATA_REQUEST'
export const GET_PROCEDURE_DRILL_DATA_ERROR = 'GET_PROCEDURE_DRILL_DATA_ERROR'
export const GET_PROCEDURE_DRILL_DATA_SUCCESS = 'GET_PROCEDURE_DRILL_DATA_SUCCESS'

export const CLEAR_PROCEDURE_REDUCER = 'CLEAR_PROCEDURE_REDUCER'

// -------------- Monitoring regions page

export const GET_DATA_FOR_MONITORING_REGIONS_PAGE_REQUEST = 'GET_DATA_FOR_MONITORING_REGIONS_PAGE_REQUEST'
export const GET_DATA_FOR_MONITORING_REGIONS_PAGE_ERROR = 'GET_DATA_FOR_MONITORING_REGIONS_PAGE_ERROR'
export const GET_DATA_FOR_MONITORING_REGIONS_PAGE_SUCCESS = 'GET_DATA_FOR_MONITORING_REGIONS_PAGE_SUCCESS'

export const GET_REGIONS_DATA_FOR_MONITORING_REGIONS_PAGE_REQUEST = 'GET_REGIONS_DATA_FOR_MONITORING_REGIONS_PAGE_REQUEST'
export const GET_REGIONS_DATA_FOR_MONITORING_REGIONS_PAGE_ERROR = 'GET_REGIONS_DATA_FOR_MONITORING_REGIONS_PAGE_ERROR'
export const GET_REGIONS_DATA_FOR_MONITORING_REGIONS_PAGE_SUCCESS = 'GET_REGIONS_DATA_FOR_MONITORING_REGIONS_PAGE_SUCCESS'

export const GET_BAR_CHART_DATA_MONITORING_REGIONS_PAGE_REQUEST = 'GET_BAR_CHART_DATA_MONITORING_REGIONS_PAGE_REQUEST'
export const GET_BAR_CHART_DATA_MONITORING_REGIONS_PAGE_ERROR = 'GET_BAR_CHART_DATA_MONITORING_REGIONS_PAGE_ERROR'
export const GET_BAR_CHART_DATA_MONITORING_REGIONS_PAGE_SUCCESS = 'GET_BAR_CHART_DATA_MONITORING_REGIONS_PAGE_SUCCESS'

// -------------- Monitoring types page

export const GET_DATA_FOR_MONITORING_TYPES_PAGE_REQUEST = 'GET_DATA_FOR_MONITORING_TYPES_PAGE_REQUEST'
export const GET_DATA_FOR_MONITORING_TYPES_PAGE_SUCCESS = 'GET_DATA_FOR_MONITORING_TYPES_PAGE_SUCCESS'
export const GET_DATA_FOR_MONITORING_TYPES_PAGE_ERROR = 'GET_DATA_FOR_MONITORING_TYPES_PAGE_ERROR'

// -------------- Mapping types
export const GET_MAPPINGS_REQUEST = 'GET_MAPPINGS_REQUEST'
export const GET_MAPPINGS_SUCCESS = 'GET_MAPPINGS_SUCCESS'
export const GET_MAPPINGS_ERROR = 'GET_MAPPINGS_ERROR'

// -------------- Monitoring coverage page

export const GET_DATA_FOR_MONITORING_COVERAGE_PAGE_REQUEST = 'GET_DATA_FOR_MONITORING_COVERAGE_PAGE_REQUEST'
export const GET_DATA_FOR_MONITORING_COVERAGE_PAGE_SUCCESS = 'GET_DATA_FOR_MONITORING_COVERAGE_PAGE_SUCCESS'
export const GET_DATA_FOR_MONITORING_COVERAGE_PAGE_ERROR = 'GET_DATA_FOR_MONITORING_COVERAGE_PAGE_ERROR'

export const GET_DATA_FOR_RESULTS_MONITORING_PAGE_REQUEST = 'GET_DATA_FOR_RESULTS_MONITORING_PAGE_REQUEST'
export const GET_DATA_FOR_RESULTS_MONITORING_PAGE_SUCCESS = 'GET_DATA_FOR_RESULTS_MONITORING_PAGE_SUCCESS'
export const GET_DATA_FOR_RESULTS_MONITORING_PAGE_ERROR = 'GET_DATA_FOR_RESULTS_MONITORING_PAGE_ERROR'

export const GET_DATA_FOR_RESULTS_BY_OFFICES_PAGE_REQUEST = 'GET_DATA_FOR_RESULTS_BY_OFFICES_PAGE_REQUEST'
export const GET_DATA_FOR_RESULTS_BY_OFFICES_PAGE_SUCCESS = 'GET_DATA_FOR_RESULTS_BY_OFFICES_PAGE_SUCCESS'
export const GET_DATA_FOR_RESULTS_BY_OFFICES_PAGE_ERROR = 'GET_DATA_FOR_RESULTS_BY_OFFICES_PAGE_ERROR'

export const GET_DATA_FOR_TYPE_OF_VIOLATION_PAGE_REQUEST = 'GET_DATA_FOR_TYPE_OF_VIOLATION_PAGE_REQUEST'
export const GET_DATA_FOR_TYPE_OF_VIOLATION_PAGE_SUCCESS = 'GET_DATA_FOR_TYPE_OF_VIOLATION_PAGE_SUCCESS'
export const GET_DATA_FOR_TYPE_OF_VIOLATION_PAGE_ERROR = 'GET_DATA_FOR_TYPE_OF_VIOLATION_PAGE_ERROR'

export const GET_DATA_FOR_RESULT_SOURCES_PAGE_REQUEST = 'GET_DATA_FOR_RESULT_SOURCES_PAGE_REQUEST'
export const GET_DATA_FOR_RESULT_SOURCES_PAGE_SUCCESS = 'GET_DATA_FOR_RESULT_SOURCES_PAGE_SUCCESS'
export const GET_DATA_FOR_RESULT_SOURCES_PAGE_ERROR = 'GET_DATA_FOR_RESULT_SOURCES_PAGE_ERROR'

export const GET_DATA_FOR_PROCESS_DURATION_PAGE_REQUEST = 'GET_DATA_FOR_PROCESS_DURATION_PAGE_REQUEST'
export const GET_DATA_FOR_PROCESS_DURATION_PAGE_SUCCESS = 'GET_DATA_FOR_PROCESS_DURATION_PAGE_SUCCESS'
export const GET_DATA_FOR_PROCESS_DURATION_PAGE_ERROR = 'GET_DATA_FOR_PROCESS_DURATION_PAGE_ERROR'
