// TEMPLATE
export const UPDATE_TEMPLATES_STORE_DATA = 'UPDATE_TEMPLATES_STORE_DATA'

export const GET_TEMPLATES_REQUEST = 'GET_TEMPLATES_REQUEST'
export const GET_TEMPLATES_SUCCESS = 'GET_TEMPLATES_SUCCESS'
export const GET_TEMPLATES_FAILED = 'GET_TEMPLATES_FAILED'

export const GET_TEMPLATE_BY_ID_REQUEST = 'GET_TEMPLATE_BY_ID_REQUEST'
export const GET_TEMPLATE_BY_ID_SUCCESS = 'GET_TEMPLATE_BY_ID_SUCCESS'
export const GET_TEMPLATE_BY_ID_FAILED = 'GET_TEMPLATE_BY_ID_FAILED'

export const GET_BASE_TEMPLATE_BY_ID_REQUEST = 'GET_BASE_TEMPLATE_BY_ID_REQUEST'
export const GET_BASE_TEMPLATE_BY_ID_SUCCESS = 'GET_BASE_TEMPLATE_BY_ID_SUCCESS'
export const GET_BASE_TEMPLATE_BY_ID_FAILED = 'GET_BASE_TEMPLATE_BY_ID_FAILED'

export const DELETE_TEMPLATE_BY_ID_REQUEST = 'DELETE_TEMPLATE_BY_ID_REQUEST'
export const DELETE_TEMPLATE_BY_ID_SUCCESS = 'DELETE_TEMPLATE_BY_ID_SUCCESS'
export const DELETE_TEMPLATE_BY_ID_FAILED = 'DELETE_TEMPLATE_BY_ID_FAILED'

export const UPDATE_TEMPLATE_REQUEST = 'UPDATE_TEMPLATE_REQUEST'
export const UPDATE_TEMPLATE_SUCCESS = 'UPDATE_TEMPLATE_SUCCESS'
export const UPDATE_TEMPLATE_FAILED = 'UPDATE_TEMPLATE_FAILED'

export const SAVE_TEMPLATES_REQUEST = 'SAVE_TEMPLATES_REQUEST'
export const SAVE_TEMPLATES_SUCCESS = 'SAVE_TEMPLATES_SUCCESS'
export const SAVE_TEMPLATES_FAILED = 'SAVE_TEMPLATES_FAILED'

export const SAVE_TEMPLATE_AUDITOR_REQUEST = 'SAVE_TEMPLATE_AUDITOR_REQUEST'
export const SAVE_TEMPLATE_AUDITOR_SUCCESS = 'SAVE_TEMPLATE_AUDITOR_SUCCESS'
export const SAVE_TEMPLATE_AUDITOR_FAILED = 'SAVE_TEMPLATE_AUDITOR_FAILED'

export const GET_TEMPLATES_TYPES_REQUEST = 'GET_TEMPLATES_TYPES_REQUEST'
export const GET_TEMPLATES_TYPES_SUCCESS = 'GET_TEMPLATES_TYPES_SUCCESS'
export const GET_TEMPLATES_TYPES_FAILED = 'GET_TEMPLATES_TYPES_FAILED'

// CATEGORY
export const GET_CATEGORIES_OF_TEMPLATES_BY_ID_REQUEST = 'GET_CATEGORIES_OF_TEMPLATES_BY_ID_REQUEST'
export const GET_CATEGORIES_OF_TEMPLATES_BY_ID_SUCCESS = 'GET_CATEGORIES_OF_TEMPLATES_BY_ID_SUCCESS'
export const GET_CATEGORIES_OF_TEMPLATES_BY_ID_FAILED = 'GET_CATEGORIES_OF_TEMPLATES_BY_ID_FAILED'
export const GET_CATEGORIES_OF_TEMPLATES_BY_ID_CLEAR = 'GET_CATEGORIES_OF_TEMPLATES_BY_ID_CLEAR'

export const GET_CATEGORIES_OF_BASE_TEMPLATES_BY_ID_REQUEST = 'GET_CATEGORIES_OF_BASE_TEMPLATES_BY_ID_REQUEST'
export const GET_CATEGORIES_OF_BASE_TEMPLATES_BY_ID_SUCCESS = 'GET_CATEGORIES_OF_BASE_TEMPLATES_BY_ID_SUCCESS'
export const GET_CATEGORIES_OF_BASE_TEMPLATES_BY_ID_FAILED = 'GET_CATEGORIES_OF_BASE_TEMPLATES_BY_ID_FAILED'
export const GET_CATEGORIES_OF_BASE_TEMPLATES_BY_ID_CLEAR = 'GET_CATEGORIES_OF_BASE_TEMPLATES_BY_ID_CLEAR'

export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST'
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS'
export const UPDATE_CATEGORY_FAILED = 'UPDATE_CATEGORY_FAILED'

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED'

export const SAVE_CATEGORY_REQUEST = 'SAVE_CATEGORY_REQUEST'
export const SAVE_CATEGORY_SUCCESS = 'SAVE_CATEGORY_SUCCESS'
export const SAVE_CATEGORY_FAILED = 'SAVE_CATEGORY_FAILED'
export const SAVE_CATEGORY_CLEAR = 'SAVE_CATEGORY_CLEAR'

//QUESTION
export const GET_QUESTIONS_OF_CATEGORY_BY_ID_REQUEST = 'GET_QUESTIONS_OF_CATEGORY_BY_ID_REQUEST'
export const GET_QUESTIONS_OF_CATEGORY_BY_ID_SUCCESS = 'GET_QUESTIONS_OF_CATEGORY_BY_ID_SUCCESS'
export const GET_QUESTIONS_OF_CATEGORY_BY_ID_FAILED = 'GET_QUESTIONS_OF_CATEGORY_BY_ID_FAILED'

export const SAVE_QUESTION_REQUEST = 'SAVE_QUESTION_REQUEST'
export const SAVE_QUESTION_SUCCESS = 'SAVE_QUESTION_SUCCESS'
export const SAVE_QUESTION_FAILED = 'SAVE_QUESTION_FAILED'
export const SAVE_QUESTION_CLEAR = 'SAVE_QUESTION_CLEAR'

export const UPDATE_QUESTION_REQUEST = 'UPDATE_QUESTION_REQUEST'
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS'
export const UPDATE_QUESTION_FAILED = 'UPDATE_QUESTION_FAILED'

export const DELETE_QUESTION_REQUEST = 'DELETE_QUESTION_REQUEST'
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS'
export const DELETE_QUESTION_FAILED = 'DELETE_QUESTION_FAILED'