export const CHANGE_NAVIGATION_KEY = 'CHANGE_NAVIGATION_KEY'
export const CHANGE_NAVIGATION_MENU_SIZE = 'CHANGE_NAVIGATION_MENU_SIZE'
export const CHANGE_BREADCRUMB_OPTIONS = 'CHANGE_BREADCRUMB_OPTIONS'
export const SET_USER_DISABLED_ERROR = 'SET_USER_DISABLED_ERROR'